const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict');
require.extensions['.ts']=(mod,path)=>mod._compile(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,path);
const {normalizePreferences,validateBackup,readStored,storeValue}=require('../lib/preferences.ts');
const {evaluateSourceAlerts,aggregateYearly}=require('../lib/market.ts');
assert.deepEqual(normalizePreferences({threshold:-5,minVolume:NaN,density:'bad',selected:'../secret',desktop:'yes',sort:'asc',sound:true}),{sort:'asc',sound:true});
assert.throws(()=>validateBackup({app:'other',version:2,favorites:[],alerts:[]}));
assert.throws(()=>validateBackup({app:'币观',version:2,favorites:['bitcoin'],alerts:[{target:-1}]}));
const backup=validateBackup({app:'币观',version:2,favorites:['bitcoin','bitcoin'],alerts:[],preferences:{density:'compact'},chart:{bar:'1Y',ma:false,windowSize:60}});
assert.deepEqual(backup.favorites,['bitcoin']);assert.equal(backup.chart.bar,'1Y');assert.equal(backup.chart.windowSize,60);
global.localStorage={getItem:()=>'{bad',setItem:()=>{throw new Error('quota')}};
assert.deepEqual(readStored('x',[]),[]);assert.equal(storeValue('x',{}),false);
const now=Date.now(),coin=(price)=>({id:'bitcoin',current_price:price,last_updated:new Date(now).toISOString()}),alert={id:'1',coinId:'bitcoin',symbol:'BTC',direction:'above',target:105,createdAt:now};
const result=evaluateSourceAlerts([alert,{...alert,id:'2',source:'okx'}],[coin(100)],[coin(110)],now,true,true);
assert.equal(result[0].triggeredAt,undefined);assert.equal(result[1].triggeredPrice,110);
assert.equal(evaluateSourceAlerts([alert],[coin(110)],[],now,false,true)[0].triggeredAt,undefined);
assert.equal(evaluateSourceAlerts([{...alert,source:'okx'}],[coin(110)],[coin(110)],now,true,false)[0].triggeredAt,undefined);
const year=2020,months=Array.from({length:12},(_,i)=>({time:Date.UTC(year,i,1)-8*3600000,open:10,high:15,low:8,close:12,volume:1,complete:true}));
assert.equal(aggregateYearly(months)[0].complete,true);assert.equal(aggregateYearly(months.slice(0,11))[0].complete,false);
const currentYear=new Date(now+8*3600000).getUTCFullYear();assert.equal(aggregateYearly([{...months[0],time:Date.UTC(currentYear,0,1)-8*3600000}])[0].complete,false);
console.log('PASS: backup validation, corrupt storage, source-isolated alerts, failed feed suppression, complete and partial yearly candles.');
